# 米游社配置
mihoyo:
  cookie: "your cookie here"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0)"
  nickname: "旅行者1号"

# 服务器配置
server:
  port: 8080

database:
  # 格式： 用户名： 密码@tcp(主机:端口)/数据库名
  dsn: "root:123456@tcp(127.0.0.1:3306)/go_70_days?charset=utf8mb4&parseTime=True&loc=Local"